aruco_image_homography_node:
  ros__parameters:
    image_path: ""
    image_topic: "/camera3/image_raw"
    detection_topic: "/yolo/detections"
    topview_topic: "/cctv/topview_image"
    output_yaml: "config/image_to_floor.yaml"
    aruco_dictionary: "DICT_4X4_250"
    marker_ids: [1, 2, 3, 4]
    marker_floor_points: [0.0, 0.0,
                          1.67, 0.0,
                          1.67, 1.65,
                          0.0, 1.65]
    floor_frame: "floor"
    scale: 1000.0
    margin: 100
    world_width: 1.67
    world_height: 1.65
    publish_topview: true
